package com.autoloan.security.config;

public enum SecurityRoles {
    ADMIN,
    MANAGER_SUPPLY,
    MANAGER_CUSTOMER, GET_CUSTOMER, ALL_CUSTOMER, ADD_CUSTOMER, UPDATE_CUSTOMER, DELETE_CUSTOMER,
    MANAGER_GROUP_PRODUCT, GET_GROUP_PRODUCT, ALL_GROUP_PRODUCT, ADD_GROUP_PRODUCT, UPDATE_GROUP_PRODUCT, DELETE_GROUP_PRODUCT,
    MANAGER_ITEM_ORDER, GET_ITEM_ORDER, ALL_ITEM_ORDER, ADD_ITEM_ORDER, UPDATE_ITEM_ORDER, DELETE_ITEM_ORDER,
    MANAGER_ORDER, GET_ORDER, ALL_ORDER, ADD_ORDER, UPDATE_ORDER, DELETE_ORDER,
    MANAGER_PRODUCT, GET_PRODUCT, ALL_PRODUCT, ADD_PRODUCT, UPDATE_PRODUCT, DELETE_PRODUCT,
    MANAGER_TAX, GET_TAX, ALL_TAX, ADD_TAX, UPDATE_TAX, DELETE_TAX,
}